### ISSUE TITLE
Failure to compile on linux 9 with OCS-16

### ISSUE THREAD

**Issue by jfletche** [mpeppler/sybperl#8] opened 2024-03-27 15:22 UTC
This is an Alma9 system with ASE16 client SDK installed. Any suggestions?

perl -version
This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-thread-multi

# make
cp lib/sybperl.pl blib/lib/sybperl.pl
cp lib/sql.pl blib/lib/sql.pl
cp lib/ctutil.pl blib/lib/ctutil.pl
cp lib/sybutil.pl blib/lib/sybutil.pl
make[1]: Entering directory '/var/tmp/sybperl-2.20/BCP'
cp BCP.pm ../blib/lib/Sybase/BCP.pm
Manifying 1 pod document
make[1]: Leaving directory '/var/tmp/sybperl-2.20/BCP'
make[1]: Entering directory '/var/tmp/sybperl-2.20/BLK'
cp BLK.pm ../blib/lib/Sybase/BLK.pm
Manifying 1 pod document
make[1]: Leaving directory '/var/tmp/sybperl-2.20/BLK'
make[1]: Entering directory '/var/tmp/sybperl-2.20/CTlib'
cp CTlib.pm ../blib/lib/Sybase/CTlib.pm
AutoSplitting ../blib/lib/Sybase/CTlib.pm (../blib/lib/auto/Sybase/CTlib)
Running Mkbootstrap for CTlib ()
chmod 644 "CTlib.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- CTlib.bs ../blib/arch/auto/Sybase/CTlib/CTlib.bs 644
"/usr/bin/perl" "/usr/share/perl5/vendor_perl/ExtUtils/xsubpp" -prototypes -typemap '/usr/share/perl5/ExtUtils/typemap'  CTlib.xs > CTlib.xsc
mv CTlib.xsc CTlib.c
gcc -c  -I/usr/sybase/include -D_REENTRANT -D_GNU_SOURCE -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fwrapv -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g   -DVERSION=\"2.20\" -DXS_VERSION=\"2.20\" -fPIC "-I/usr/lib64/perl5/CORE"  -DCTLIBVS=100 -DSYBPLVER='"2.20"' -DDO_TIE -DSYB_LP64 CTlib.c
CTlib.xs: In function ‘newdbh’:
CTlib.xs:408:13: warning: unused variable ‘count’ [-Wunused-variable]
  408 |         int count;
      |             ^~~~~
CTlib.xs: In function ‘_convert’:
CTlib.xs:687:43: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
  687 |         if ((debug_level & TRACE_CONVERT) && retcode != CS_SUCCEED || reslen
CTlib.xs: In function ‘cleanUp’:
CTlib.xs:1038:41: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
 1038 |                                         && info->coldata[i].type == CS_CHAR_TYPE
CTlib.xs: In function ‘describe’:
CTlib.xs:1350:25: warning: label ‘DoFloat’ defined but not used [-Wunused-label]
 1350 |                         DoFloat: ;
      |                         ^~~~~~~
CTlib.xs: In function ‘fetch_data’:
CTlib.xs:1540:41: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘CS_INT’ {aka ‘int’} [-Wformat=]
 1540 |                         fprintf(stdout, "Error on row %ld.\n", row_count);
      |                                         ^~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~
      |                                                                |
      |                                                                CS_INT {aka int}
CTlib.xs: In function ‘get_cs_msg’:
CTlib.xs:1716:25: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘unsigned int’ [-Wformat=]
 1716 |         fprintf(stderr, "Message number: LAYER = (%ld) ORIGIN = (%ld) ", CS_LAYER(
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CTlib.xs:1716:25: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘unsigned int’ [-Wformat=]
 1716 |         fprintf(stderr, "Message number: LAYER = (%ld) ORIGIN = (%ld) ", CS_LAYER(
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CTlib.xs:1718:25: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘unsigned int’ [-Wformat=]
 1718 |         fprintf(stderr, "SEVERITY = (%ld) NUMBER = (%ld)\n", CS_SEVERITY(
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CTlib.xs:1718:25: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘unsigned int’ [-Wformat=]
 1718 |         fprintf(stderr, "SEVERITY = (%ld) NUMBER = (%ld)\n", CS_SEVERITY(
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CTlib.xs:1674:20: warning: unused variable ‘retval’ [-Wunused-variable]
 1674 |         CS_RETCODE retval;
      |                    ^~~~~~
CTlib.xs: In function ‘cslibmsg_cb’:
CTlib.xs:1807:25: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘unsigned int’ [-Wformat=]
 1807 |         fprintf(stderr, "Message number: LAYER = (%ld) ORIGIN = (%ld) ", CS_LAYER(
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CTlib.xs:1807:25: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘unsigned int’ [-Wformat=]
 1807 |         fprintf(stderr, "Message number: LAYER = (%ld) ORIGIN = (%ld) ", CS_LAYER(
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CTlib.xs:1809:25: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘unsigned int’ [-Wformat=]
 1809 |         fprintf(stderr, "SEVERITY = (%ld) NUMBER = (%ld)\n", CS_SEVERITY(
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CTlib.xs:1809:25: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘unsigned int’ [-Wformat=]
 1809 |         fprintf(stderr, "SEVERITY = (%ld) NUMBER = (%ld)\n", CS_SEVERITY(
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CTlib.xs: In function ‘clientmsg_cb’:
CTlib.xs:1871:25: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘unsigned int’ [-Wformat=]
 1871 |         fprintf(stderr, "Message number: LAYER = (%ld) ORIGIN = (%ld) ", CS_LAYER(
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CTlib.xs:1871:25: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘unsigned int’ [-Wformat=]
 1871 |         fprintf(stderr, "Message number: LAYER = (%ld) ORIGIN = (%ld) ", CS_LAYER(
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CTlib.xs:1873:25: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘unsigned int’ [-Wformat=]
 1873 |         fprintf(stderr, "SEVERITY = (%ld) NUMBER = (%ld)\n", CS_SEVERITY(
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CTlib.xs:1873:25: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘unsigned int’ [-Wformat=]
 1873 |         fprintf(stderr, "SEVERITY = (%ld) NUMBER = (%ld)\n", CS_SEVERITY(
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CTlib.xs: In function ‘servermsg_cb’:
CTlib.xs:1895:21: warning: unused variable ‘hv’ [-Wunused-variable]
 1895 |                 HV *hv;
      |                     ^~
CTlib.xs:1894:27: warning: unused variable ‘svp’ [-Wunused-variable]
 1894 |                 SV *sv, **svp;
      |                           ^~~
CTlib.xs:1975:41: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘CS_MSGNUM’ {aka ‘unsigned int’} [-Wformat=]
 1975 |                         fprintf(stderr, "Message number: %ld, Severity %ld, ",
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1976 |                                         srvmsg->msgnumber, srvmsg->severity);
      |                                         ~~~~~~~~~~~~~~~~~
      |                                               |
      |                                               CS_MSGNUM {aka unsigned int}

**Comment by mpeppler** [comment] 2024-03-28 06:58
Hi
All the compiler messages in the trace above appear to be warnings (not pretty, but not fatal). There must be something else in the compile trace/build trace that would indicate what is the actual failure.
Thanks!

**Comment by jfletche** [comment] 2024-03-28 07:01
Correct. That wasn't the full trace (for brevity). Let me see if I can get the whole thing attached. We know it builds on Alma 8.

**Comment by RajnikantML** [comment] 2024-04-01 10:19
The problem is pointing to the system compiler "gcc". When compiling the Perl module "Sybase::BCP" from source code, the Alma 9 "gcc" (version 11.4.1-2.1.el9.alma) with a CCFLAG "-Werror=format-security" would throw the following error and failed to generate the binary! In the following highlighted message, the "gcc" treated "warning" as "error" and failed the compile! In EL8 (CentOS 7/8 and Alma 8), the "gcc" (version 8.5.0-xx.el8) could compile the same set of source code ONLY with "warning", but would not fail the whole compile process and could generate the binary.


DBlib.xs:5779:15: error: format not a string literal and no format arguments **[-Werror=format-security]**
 5779 |         **croak(buff);**
DBlib.xs:5920:15: error: format not a string literal and no format arguments **[-Werror=format-security]**
 5920 |         **croak(buff);**
      |               ^~~~
cc1: some warnings being treated as errors
make[1]: *** [Makefile:327: DBlib.o] Error 1

**Comment by mpeppler** [comment] 2024-04-01 11:20
Thanks - that's interesting. The code is:

sprintf(buff, "Invalid type value (%d) for dbrpcparam()", type);
croak(buff);

so I suppose that the compiler would really like that to be merged to a single call, like this

croak(buff, "Invalid type value (%d) for dbrpcparam()", type);

My guess is that this was written that way initially because croak() could only take a literal, and not a printf() style format.

I'll see what I can do to fix this.

**Comment by mpeppler** [comment] 2024-04-01 11:55
Please try 2.21 and see if it works.

**Comment by RajnikantML** [comment] 2024-04-02 11:26
Thanks Michael. You did awesome changes in very short period. 2.21 works fine with Almalinux 9.

**Comment by mpeppler** [comment] 2024-04-07 13:08
Thanks - closing this issue.

**Closed as completed by mpeppler** 2024-04-07 13:08 UTC
